<?php

namespace Proxies\__CG__\Convert\DeviseBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Historique extends \Convert\DeviseBundle\Entity\Historique implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'id', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'ipdclient', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'nbdemande', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'datedemande', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'cible', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'source', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'cour', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'montant', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'etatip');
        }

        return array('__isInitialized__', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'id', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'ipdclient', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'nbdemande', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'datedemande', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'cible', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'source', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'cour', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'montant', '' . "\0" . 'Convert\\DeviseBundle\\Entity\\Historique' . "\0" . 'etatip');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Historique $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCible', array());

        return parent::getCible();
    }

    /**
     * {@inheritDoc}
     */
    public function getSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSource', array());

        return parent::getSource();
    }

    /**
     * {@inheritDoc}
     */
    public function getCour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCour', array());

        return parent::getCour();
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', array());

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setCible($cible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCible', array($cible));

        return parent::setCible($cible);
    }

    /**
     * {@inheritDoc}
     */
    public function setSource($source)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSource', array($source));

        return parent::setSource($source);
    }

    /**
     * {@inheritDoc}
     */
    public function setCour($cour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCour', array($cour));

        return parent::setCour($cour);
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant($montant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', array($montant));

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function setIpdclient($ipdclient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIpdclient', array($ipdclient));

        return parent::setIpdclient($ipdclient);
    }

    /**
     * {@inheritDoc}
     */
    public function getIpdclient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIpdclient', array());

        return parent::getIpdclient();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbdemande($nbdemande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbdemande', array($nbdemande));

        return parent::setNbdemande($nbdemande);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbdemande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbdemande', array());

        return parent::getNbdemande();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatedemande($datedemande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatedemande', array($datedemande));

        return parent::setDatedemande($datedemande);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatedemande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatedemande', array());

        return parent::getDatedemande();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatip($etatip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatip', array($etatip));

        return parent::setEtatip($etatip);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatip', array());

        return parent::getEtatip();
    }

}
