<?php

namespace Convert\DeviseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeviseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviseRepository extends EntityRepository
{
}
