<?php

namespace Convert\DeviseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HistoriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueRepository extends EntityRepository
{
}
